// <auto-generated />
namespace WBY.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ExtraUserInformation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExtraUserInformation));
        
        string IMigrationMetadata.Id
        {
            get { return "201410072105490_ExtraUserInformation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
