// <auto-generated />
namespace WBY.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class substancevehicle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(substancevehicle));
        
        string IMigrationMetadata.Id
        {
            get { return "201410071937395_substancevehicle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
